### ISSUE TITLE
Route validation does not work

### ISSUE THREAD

**Issue by jamrizzi** [trailsjs/trailpack-express#67]
I cannot seem to get route validation to work.

My config looks like the following . . .

```js
    config: {
      validate: {
        body: object({
          name: Joi.string()
            .min(3)
            .max(4)
            .required()
        })
      }
    }
```

**Comment by jamrizzi** [comment]
So it turns out validation works on everything but body.

**Comment by jamrizzi** [comment]
It looks like the bug was created by not handling the hapi compatible payload correctly.

**Comment by jaumard** [comment]
No in fact it's because you need to use hapi notation (at least it was designed like this) and use `payload` instead of `body`

**Comment by jamrizzi** [comment]
Express is not hapi. That's counterintuitive and confusing for express users. I think it should support both.

**Comment by jaumard** [comment]
Route definition is global to Trails project whatever the web server (and not hapi/express specific), meaning that whatever the definition you have here, it has to work for any web server under the hood. The trails team choose to base his route definition on the hapi one that's why it use payload and not body. Sure we can support body but in that case trailpack-hapi will have to support it too, but for me it's not a good thing to offer the same functionality with two different name. 

What we can do is to enhance the route definition validation here https://github.com/trailsjs/trailpack-router/blob/master/lib/schemas/route.js#L21 to add the missing validation. Like this when someone put `body` it will say that it's forbidden. At least there will be a real error instead of just ignoring the entry.

If someone have other opinion/idea you're welcome @trailsjs/maintainers :)

**Comment by jamrizzi** [comment]
Ok, I guess that makes sense. I'm happy to at least know what the issue was. I need to use payload instead of body.
